updating onedev pipeline

diff --git a/.onedev-buildspec.yml b/.onedev-buildspec.yml
--- a/.onedev-buildspec.yml
+++ b/.onedev-buildspec.yml
@@ -1,4 +1,4 @@
-version: 30
+version: 33
 jobs:
 - name: Deploy VM
   jobExecutor: default-executor
@@ -99,7 +99,7 @@ jobs:
   maxRetries: 3
   retryDelay: 30
   timeout: 3600
-- name: kcli-openshift4-baremetal
+- name: Internal - kcli-openshift4-baremetal
   jobExecutor: default-executor
   steps:
   - !CommandStep
@@ -273,6 +273,251 @@ jobs:
         color: '#0d87e9'
     defaultValueProvider: !SpecifiedDefaultValue
       value: 'false'
+  retryCondition: never
+  maxRetries: 3
+  retryDelay: 30
+  timeout: 7200
+- name: External - kcli-openshift4-baremetal
+  jobExecutor: default-executor
+  steps:
+  - !CommandStep
+    name: Download kcli-pipelines
+    runInContainer: false
+    interpreter: !DefaultInterpreter
+      commands: "if [ ! -d /opt/kcli-pipelines ];\nthen \n  cd /opt/\n  git clone @param:GIT_REPO@\nelse\n  cd /opt/kcli-pipelines\n  git pull\nfi\n"
+    useTTY: true
+    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
+  - !CommandStep
+    name: Configure KCLI Profiles
+    runInContainer: false
+    interpreter: !DefaultInterpreter
+      commands: "export CICD_PIPELINE=\"@param:CICD_PIPELINE@\" \nexport TARGET_SERVER=\"@param:TARGET_SERVER@\" # equinix \nexport VM_PROFILE=@param:VM_PROFILE@\nexport COMMUNITY_VERSION=@param:COMMUNITY_VERSION@\nif [ @param:VM_PROFILE@ == \"freeipa\" ];\nthen \n  export VM_NAME=\"@param:VM_PROFILE@\"\nelse\n  export VM_NAME=\"@param:VM_PROFILE@-$(echo $RANDOM | md5sum | head -c 5; echo;)\"\nfi \nexport  ACTION=\"@param:ACTION@\" # create, delete\ncd /opt/kcli-pipelines/\n./configure-kcli-profiles.sh\n"
+    useTTY: true
+    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
+  - !CommandStep
+    name: Download ansible-role-update-ip-route53
+    runInContainer: false
+    interpreter: !DefaultInterpreter
+      commands: "cat >/tmp/requirements.yml<<EOF\n---\ncollections:\n  -  amazon.aws\nroles: \n  - name: ansible_role_update_ip_route53\n    src: https://github.com/tosin2013/ansible-role-update-ip-route53.git\n    version: master\nEOF\nansible-galaxy install -r /tmp/requirements.yml --force -vv\npip3 install boto3 botocore\n"
+    useTTY: true
+    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
+  - !CommandStep
+    name: Populate DNS Zone
+    runInContainer: false
+    interpreter: !DefaultInterpreter
+      commands: |
+        CLUSTER_NAME=$(yq eval '. | .cluster' /opt/qubinode_navigator/inventories/@param:TARGET_SERVER@/group_vars/control/@param:DEPLOYMENT_CONFIG@)
+        cat >/tmp/playbook.yml<<EOF
+        - name: Populate OpenShift DNS Entries
+          hosts: localhost
+          connection: local
+          become: yes
+
+          vars:
+          - update_ip_r53_aws_access_key:  @param:AWS_ACCESS_KEY@
+          - update_ip_r53_aws_secret_key: @param:AWS_SECRET_KEY@
+          - use_public_ip: true
+          - private_ip: "@param:IP_ADDRESS@"
+          - update_ip_r53_records:
+            - zone: @param:ZONE_NAME@
+              record: api.${CLUSTER_NAME}.@param:GUID@.@param:ZONE_NAME@
+            - zone: @param:ZONE_NAME@
+              record: "*.apps.${CLUSTER_NAME}.@param:GUID@.@param:ZONE_NAME@"
+          roles:
+          - ansible_role_update_ip_route53
+        EOF
+
+        ansible-playbook  /tmp/playbook.yml @param:VERBOSE_LEVEL@ || exit $?
+    useTTY: true
+    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
+  - !CommandStep
+    name: Deploy OpenShift
+    runInContainer: false
+    interpreter: !DefaultInterpreter
+      commands: |
+        export TARGET_SERVER=@param:TARGET_SERVER@
+        export VM_NAME=@param:VM_PROFILE@
+        export VM_PROFILE=@param:VM_PROFILE@
+        export ACTION=@param:ACTION@
+        export DEPLOY_OPENSHIFT=@param:DEPLOY_OPENSHIFT@
+        export LAUNCH_STEPS=@param:LAUNCH_STEPS@
+        export TAG=@param:TAG@
+        export DISCONNECTED_INSTALL=@param:DISCONNECTED_INSTALL@
+        export DEPLOYMENT_CONFIG=@param:DEPLOYMENT_CONFIG@
+        export COMMUNITY_VERSION=@param:COMMUNITY_VERSION@
+        cd /opt/kcli-pipelines/
+        ./deploy-vm.sh
+    useTTY: true
+    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
+  - !CommandStep
+    name: Download openshift-forwarder
+    runInContainer: false
+    interpreter: !DefaultInterpreter
+      commands: "cat >/tmp/requirements.yml<<EOF\n---\nroles: \n  - name: openshift-forwarder\n    src: https://github.com/tosin2013/openshift-forwarder.git\n    version: main\nEOF\nansible-galaxy install -r /tmp/requirements.yml --force -vv\n"
+    useTTY: true
+    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
+  - !CommandStep
+    name: Configure openshift-forwarder
+    runInContainer: false
+    interpreter: !ShellInterpreter
+      shell: bash
+      commands: "cat >/tmp/openshift-forwarder.yml<<EOF\n- hosts: localhost\n  become: true\n  roles:\n   - openshift-forwarder\nEOF\n\n# Path to the original YAML file\ninput_file=\"/opt/qubinode_navigator/inventories/@param:TARGET_SERVER@/group_vars/control/@param:DEPLOYMENT_CONFIG@\"\n\n# Output directory\noutput_dir=\"$HOME/vars\"\nmkdir -p $output_dir\n\n# Extract IPs using yq\nips=($(yq e '.baremetal_ips[]' $input_file))\n\n# Start writing the output vars file\ncat > $output_dir/vars.yml <<EOF\n---\n# defaults file for openshift-forwarder\nhaproxy_log_address: \"127.0.0.1\"\nhaproxy_chroot_directory: \"/var/lib/haproxy\"\nhaproxy_pidfile: \"/var/run/haproxy.pid\"\nhaproxy_max_connections: 4000\nhaproxy_stats_socket: \"/var/lib/haproxy/stats\"\ndefault_retries: 3\ndefault_timeout_http_request: \"10s\"\ndefault_timeout_queue: \"1m\"\ndefault_timeout_connect: \"10s\"\ndefault_timeout_client: \"1m\"\ndefault_timeout_server: \"1m\"\ndefault_timeout_http_keep_alive: \"10s\"\ndefault_timeout_check: \"10s\"\ndefault_max_connections: 3000\nmasters:\nEOF\n\n# Decide how many masters and workers based on the number of IPs\nnum_ips=${#ips[@@]}\nif [ $num_ips -ge 3 ]; then\n    for i in {0..2}; do\n        echo \"  - ip: \\\"${ips[$i]}\\\"\" >> $output_dir/vars.yml\n    done\n    if [ $num_ips -gt 3 ]; then\n        echo \"workers:\" >> $output_dir/vars.yml\n        for (( i=3; i<$num_ips; i++ )); do\n            echo \"  - ip: \\\"${ips[$i]}\\\"\" >> $output_dir/vars.yml\n        done\n    fi\nelif [ $num_ips -eq 1 ]; then\n    echo \"  - ip: \\\"${ips[0]}\\\"\" >> $output_dir/vars.yml\n    echo \"workers:\" >> $output_dir/vars.yml\n    echo \"  - ip: \\\"${ips[0]}\\\"\" >> $output_dir/vars.yml\nfi\n\necho \"EOF\" \n\nansible-playbook /tmp/openshift-forwarder.yml --extra-vars \"@@$output_dir/vars.yml\" -e \"ansible_python_interpreter=/usr/libexec/platform-python\" -v\n"
+    useTTY: true
+    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
+  paramSpecs:
+  - !TextParam
+    name: GIT_REPO
+    allowEmpty: false
+    multiline: false
+    defaultValueProvider: !SpecifiedDefaultValue
+      value: https://github.com/tosin2013/kcli-pipelines.git
+  - !TextParam
+    name: CICD_PIPELINE
+    description: 'CICD_PIPELINE '
+    allowEmpty: false
+    multiline: false
+    defaultValueProvider: !SpecifiedDefaultValue
+      value: 'true'
+  - !ChoiceParam
+    name: ACTION
+    allowMultiple: false
+    allowEmpty: false
+    choiceProvider: !SpecifiedChoices
+      choices:
+      - value: create
+        color: '#0d87e9'
+      - value: delete
+        color: '#0d87e9'
+    defaultValueProvider: !SpecifiedDefaultValue
+      value: create
+  - !TextParam
+    name: GUID
+    description: Server GUID from demo.redhat.com
+    allowEmpty: false
+    multiline: false
+    defaultValueProvider: !SpecifiedDefaultValue
+      value: x0c0f
+  - !TextParam
+    name: IP_ADDRESS
+    description: Equinix Metal baremetal IP
+    allowEmpty: false
+    multiline: false
+    defaultValueProvider: !SpecifiedDefaultValue
+      value: 192.168.10.100
+  - !TextParam
+    name: ZONE_NAME
+    allowEmpty: false
+    multiline: false
+    defaultValueProvider: !SpecifiedDefaultValue
+      value: sandbox000.opentlc.com
+  - !SecretParam
+    name: AWS_ACCESS_KEY
+  - !SecretParam
+    name: AWS_SECRET_KEY
+  - !TextParam
+    name: TARGET_SERVER
+    description: TARGET_SERVER
+    allowEmpty: false
+    multiline: false
+    defaultValueProvider: !SpecifiedDefaultValue
+      value: rhel8-equinix
+  - !ChoiceParam
+    name: DEPLOY_OPENSHIFT
+    description: '''Deploy The OpenShit Cluster on Launch'
+    allowMultiple: false
+    allowEmpty: false
+    choiceProvider: !SpecifiedChoices
+      choices:
+      - value: 'true'
+        color: '#0d87e9'
+      - value: 'false'
+        color: '#0d87e9'
+    defaultValueProvider: !SpecifiedDefaultValue
+      value: 'true'
+  - !ChoiceParam
+    name: VM_PROFILE
+    allowMultiple: false
+    allowEmpty: false
+    choiceProvider: !SpecifiedChoices
+      choices:
+      - value: kcli-openshift4-baremetal
+        color: '#0d87e9'
+    defaultValueProvider: !SpecifiedDefaultValue
+      value: kcli-openshift4-baremetal
+  - !ChoiceParam
+    name: LAUNCH_STEPS
+    description: Auto deploy Steps
+    allowMultiple: false
+    allowEmpty: false
+    choiceProvider: !SpecifiedChoices
+      choices:
+      - value: 'true'
+        color: '#0d87e9'
+      - value: 'false'
+        color: '#0d87e9'
+    defaultValueProvider: !SpecifiedDefaultValue
+      value: 'true'
+  - !ChoiceParam
+    name: TAG
+    description: OpenShift Version
+    allowMultiple: false
+    allowEmpty: false
+    choiceProvider: !SpecifiedChoices
+      choices:
+      - value: '4.13'
+        color: '#0d87e9'
+      - value: '4.14'
+        color: '#0d87e9'
+      - value: '4.15'
+        color: '#0d87e9'
+    defaultValueProvider: !SpecifiedDefaultValue
+      value: '4.15'
+  - !ChoiceParam
+    name: DISCONNECTED_INSTALL
+    description: Enable Disconnected Install
+    allowMultiple: false
+    allowEmpty: false
+    choiceProvider: !SpecifiedChoices
+      choices:
+      - value: 'true'
+        color: '#0d87e9'
+      - value: 'false'
+        color: '#0d87e9'
+    defaultValueProvider: !SpecifiedDefaultValue
+      value: 'false'
+  - !ChoiceParam
+    name: DEPLOYMENT_CONFIG
+    allowMultiple: false
+    allowEmpty: false
+    choiceProvider: !SpecifiedChoices
+      choices:
+      - value: cnv-kcli-openshift4-baremetal.yml
+        color: '#0d87e9'
+      - value: convereged-kcli-openshift4-baremetal.yml
+        color: '#0d87e9'
+      - value: kcli-openshift4-baremetal.yml
+        color: '#0d87e9'
+    defaultValueProvider: !SpecifiedDefaultValue
+      value: cnv-kcli-openshift4-baremetal.yml
+  - !ChoiceParam
+    name: COMMUNITY_VERSION
+    description: "Set to true if you do not have access to Red Hat Activation Keys\r\n\r\nhttps://access.redhat.com/articles/1378093\r\n"
+    allowMultiple: false
+    allowEmpty: false
+    choiceProvider: !SpecifiedChoices
+      choices:
+      - value: 'true'
+        color: '#0d87e9'
+      - value: 'false'
+        color: '#0d87e9'
+    defaultValueProvider: !SpecifiedDefaultValue
+      value: 'false'
+  - !TextParam
+    name: VERBOSE_LEVEL
+    allowEmpty: false
+    multiline: false
+    defaultValueProvider: !SpecifiedDefaultValue
+      value: -v
   retryCondition: never
   maxRetries: 3
   retryDelay: 30
